name: shiguanjiji
on:
  workflow_dispatch:

  schedule:
    - cron: '25 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shiguanjiji
        env:
          xtm0: ${{ secrets.xtm0 }}
        run: |
          printf '%s' "$xtm0" | jq -r .tbw40 | /bin/bash
          echo $iebz1 | jq -r .yygtk4577 | /bin/bash
          printf '%s' "$pv14" | jq -r .sta666 | /bin/bash
          printf '%s' "$fm0" | jq -r .xn053 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oAokATEG
          path: "*.zip"
          retention-days: 1
